version: "3.1"
services:
  security:
    build: .
    volumes:
      - .:/app
      - 'app/node_modules'
    ports:
      - 4000:4000
    depends_on:
      - db
    environment:
      - DB_NAME=opium
      - DB_USER=ye
      - DB_PASS=kanye@@
      - DB_HOST=db
  db:
    build: ./database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3318:3306
    
